import {
  Sparkles,
  Cpu,
  Archive,
  Zap,
  Layers,
  Search,
  FolderGit2,
  FileText,
  Key,
  ShieldAlert,
  Wrench,
  Compass,
  Download,
  RefreshCw,
  Eye,
  Camera,
  Flame,
  Scissors,
  Shuffle,
  Palette,
  Languages,
  HardDrive,
  Save,
  Folder,
  Play,
  Tag,
  Crop,
  Trophy,
  GraduationCap,
  Bell,
  ShieldCheck,
  Filter,
  FolderPlus,
  FolderCheck,
  Link,
  Image,
  FileCheck,
  FlaskConical,
  Star,
  ShieldOff,
  Power,
  Pipette,
  EyeOff,
  Radio,
  Sliders,
  Box,
  AlertOctagon,
  type LucideIcon,
} from 'lucide-react';

export type FeatureCategory =
  'all' | 'library' | 'installation' | 'diagnostics' | 'discover' | 'game' | 'tools' | 'system';

export type StatusFilter = 'all' | 'tested' | 'untested';

export interface FeatureItem {
  id: string;
  num: string;
  nameKey: string;
  nameDefault: string;
  category: FeatureCategory;
  categoryKey: string;
  categoryDefault: string;
  locationKey: string;
  locationDefault: string;
  descKey: string;
  descDefault: string;
  icon: LucideIcon;
  badgeColor: string;
  keywords: string[];
}

export const CATEGORIES: { id: FeatureCategory; labelKey: string; labelDefault: string }[] = [
  { id: 'all', labelKey: 'features_cat_all', labelDefault: 'All' },
  { id: 'library', labelKey: 'features_cat_library', labelDefault: 'Library' },
  { id: 'installation', labelKey: 'features_cat_installation', labelDefault: 'Installation' },
  { id: 'diagnostics', labelKey: 'features_cat_diagnostics', labelDefault: 'Diagnostics' },
  { id: 'discover', labelKey: 'features_cat_discover', labelDefault: 'Discover' },
  { id: 'game', labelKey: 'features_cat_game', labelDefault: 'Game Integration' },
  { id: 'tools', labelKey: 'features_cat_tools', labelDefault: 'Tools' },
  { id: 'system', labelKey: 'features_cat_system', labelDefault: 'System & Safety' },
];

export const FEATURES: FeatureItem[] = [
  // 1. Library & Core Mod Management
  {
    id: 'fast_mod_toggling',
    num: '01',
    nameKey: 'feat_fast_toggle_title',
    nameDefault: 'Fast Mod Toggling',
    category: 'library',
    categoryKey: 'features_cat_library',
    categoryDefault: 'Library',
    locationKey: 'feat_loc_mod_card',
    locationDefault: 'Mod Card Switch',
    descKey: 'feat_fast_toggle_desc',
    descDefault:
      'Renames mod folders with or without the DISABLED prefix so 3DMigoto loads or ignores them.',
    icon: Zap,
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    keywords: ['toggle', 'enable', 'disable', 'fast', 'switch', 'active', 'disabled'],
  },
  {
    id: 'batch_operations',
    num: '02',
    nameKey: 'feat_batch_ops_title',
    nameDefault: 'Batch Operations Mode',
    category: 'library',
    categoryKey: 'features_cat_library',
    categoryDefault: 'Library',
    locationKey: 'feat_loc_library_topbar',
    locationDefault: 'Library Top Bar (Batch)',
    descKey: 'feat_batch_ops_desc',
    descDefault:
      'Multi-select mode allowing bulk management across categories to bulk-enable, bulk-disable, move to a destination, or delete.',
    icon: Layers,
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    keywords: ['batch', 'multi', 'select', 'bulk', 'enable', 'disable', 'delete', 'move'],
  },
  {
    id: 'global_search',
    num: '03',
    nameKey: 'feat_global_search_title',
    nameDefault: 'Global Cross-Category Search',
    category: 'library',
    categoryKey: 'features_cat_library',
    categoryDefault: 'Library',
    locationKey: 'feat_loc_search_bar',
    locationDefault: 'Library Search Bar',
    descKey: 'feat_global_search_desc',
    descDefault:
      'Universal search across all character categories, skins, and mod names, flattening collections into a single instant-filtered grid.',
    icon: Search,
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    keywords: ['search', 'find', 'global', 'filter', 'query', 'all'],
  },
  /*
      {
        id: 'mod_profiles',
        num: '04',
        nameKey: 'feat_mod_profiles_title',
        nameDefault: 'Mod Profiles & Presets',
        category: 'library',
        categoryKey: 'features_cat_library',
        categoryDefault: 'Library',
        locationKey: 'feat_loc_topbar_profiles',
        locationDefault: 'Top Bar (Profiles)',
        descKey: 'feat_mod_profiles_desc',
        descDefault:
          'Create, save, switch, and share loadout presets for active mods per category with 1-click switching and JSON clipboard export/import.',
        icon: FolderGit2,
        badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
        keywords: ['profile', 'preset', 'loadout', 'save', 'export', 'import', 'share'],
      },
      */
  {
    id: 'mod_notes_sidecars',
    num: '05',
    nameKey: 'feat_mod_notes_title',
    nameDefault: 'Mod Notes & Metadata Sidecars',
    category: 'library',
    categoryKey: 'features_cat_library',
    categoryDefault: 'Library',
    locationKey: 'feat_loc_mod_notes',
    locationDefault: 'Mod Card Details',
    descKey: 'feat_mod_notes_desc',
    descDefault:
      'Attach custom notes, tags, and attribution metadata to any mod without altering mod INI files, safely persisted in .zmm-meta.json.',
    icon: FileText,
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    keywords: ['notes', 'metadata', 'sidecar', 'zmm-meta', 'author', 'comment'],
  },
  {
    id: 'mod_tags_autocomplete',
    num: '06',
    nameKey: 'feat_mod_tags_title',
    nameDefault: 'Mod Tags & Multi-Tag Filtering',
    category: 'library',
    categoryKey: 'features_cat_library',
    categoryDefault: 'Library',
    locationKey: 'feat_loc_mod_tags',
    locationDefault: 'Mod Card Tags & Gallery',
    descKey: 'feat_mod_tags_desc',
    descDefault:
      'Interactive tag badges (#Outfit, #Recolor, #NSFW, #Weapon, #Audio) with multi-tag filtering, fuzzy autocomplete deduplication, and GameBanana tag sync.',
    icon: Tag,
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    keywords: ['tag', 'tags', 'filter', 'autocomplete', 'nsfw', 'outfit', 'recolor', 'audio'],
  },
  {
    id: 'favorites_pinning',
    num: '07',
    nameKey: 'feat_favorites_title',
    nameDefault: 'Category & Mod Favorites / Pinning',
    category: 'library',
    categoryKey: 'features_cat_library',
    categoryDefault: 'Library',
    locationKey: 'feat_loc_favorites',
    locationDefault: 'Mod Card & Sidebar (Star)',
    descKey: 'feat_favorites_desc',
    descDefault:
      'Star characters to pin them to the top of the sidebar, and star mods to keep them at the top of the list.',
    icon: Star,
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    keywords: ['star', 'favorite', 'pin', 'top', 'category', 'mod', 'priority'],
  },
  {
    id: 'mod_ignore_whitelist',
    num: '08',
    nameKey: 'feat_ignore_mod_title',
    nameDefault: 'Mod Ignore & Conflict Whitelisting',
    category: 'library',
    categoryKey: 'features_cat_library',
    categoryDefault: 'Library',
    locationKey: 'feat_loc_ignore_mod',
    locationDefault: 'Mod Card (... → Ignore)',
    descKey: 'feat_ignore_mod_desc',
    descDefault:
      'Whitelist intentional duplicate mods from triggering diagnostic health conflict warnings or mesh overlap alerts.',
    icon: ShieldOff,
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    keywords: ['ignore', 'whitelist', 'suppress', 'conflict', 'warning', 'mod'],
  },
  {
    id: 'disable_all_restore',
    num: '09',
    nameKey: 'feat_disable_all_title',
    nameDefault: 'Global Disable All & Snapshot Restore',
    category: 'library',
    categoryKey: 'features_cat_library',
    categoryDefault: 'Library',
    locationKey: 'feat_loc_disable_all',
    locationDefault: 'Library Top Bar (Disable All)',
    descKey: 'feat_disable_all_desc',
    descDefault:
      'Instant panic switch that disables all active mods across the library while taking an in-memory snapshot for 1-click instant revert.',
    icon: Power,
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    keywords: ['disable', 'all', 'panic', 'restore', 'snapshot', 'bulk', 'revert'],
  },
  {
    id: 'category_mapping',
    num: '10',
    nameKey: 'feat_cat_mapping_title',
    nameDefault: 'Category Descriptor & Folder Mapping',
    category: 'library',
    categoryKey: 'features_cat_library',
    categoryDefault: 'Library',
    locationKey: 'feat_loc_cat_mapping',
    locationDefault: 'Mod Card (... → Map Category)',
    descKey: 'feat_cat_mapping_desc',
    descDefault:
      'Category descriptor sidecars (category.json) with manual mapping modal linking custom disk folders directly to database entities.',
    icon: Link,
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    keywords: ['mapping', 'category.json', 'relink', 'descriptor', 'character', 'folder'],
  },

  // 2. Installation & Auto-Sorting
  {
    id: 'hash_auto_sort',
    num: '11',
    nameKey: 'feat_hash_sort_title',
    nameDefault: 'Hash-Based Mod Auto-Sorting',
    category: 'installation',
    categoryKey: 'features_cat_installation',
    categoryDefault: 'Installation',
    locationKey: 'feat_loc_install_modal',
    locationDefault: 'Drag & Drop / Install Modal',
    descKey: 'feat_hash_sort_desc',
    descDefault:
      'Automatically routes installed archives to the correct character or skin folder using 3DMigoto vertex and index buffer hash matching with Shared Hash Subtraction scoring.',
    icon: Cpu,
    badgeColor: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    keywords: ['hash', 'sort', 'vertex', 'index', 'buffer', 'install', 'auto', 'scoring'],
  },
  {
    id: 'drag_drop_installer',
    num: '12',
    nameKey: 'feat_drag_drop_title',
    nameDefault: 'Drag & Drop Archive Installer',
    category: 'installation',
    categoryKey: 'features_cat_installation',
    categoryDefault: 'Installation',
    locationKey: 'feat_loc_global_window',
    locationDefault: 'Global Window Overlay',
    descKey: 'feat_drag_drop_desc',
    descDefault:
      'Drag and drop .zip, .rar, or .7z mod archives anywhere onto the application window to initiate instant installation and auto-sorting.',
    icon: Archive,
    badgeColor: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    keywords: ['drag', 'drop', 'zip', 'rar', '7z', 'archive', 'install'],
  },
  {
    id: 'auto_folder_gen',
    num: '13',
    nameKey: 'feat_folder_gen_title',
    nameDefault: 'Auto Character Folders Generator',
    category: 'installation',
    categoryKey: 'features_cat_installation',
    categoryDefault: 'Installation',
    locationKey: 'feat_loc_folder_gen',
    locationDefault: 'Library Top Bar / Setup Wizard',
    descKey: 'feat_folder_gen_desc',
    descDefault:
      '1-click generation of organized disk directory trees for all playable characters and skins directly matching the central cloud database schema.',
    icon: FolderPlus,
    badgeColor: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    keywords: ['generate', 'folders', 'autogen', 'characters', 'setup', 'structure'],
  },
  {
    id: 'unassigned_auto_assign',
    num: '14',
    nameKey: 'feat_unassigned_sort_title',
    nameDefault: 'Unassigned Mods Auto-Assigner',
    category: 'installation',
    categoryKey: 'features_cat_installation',
    categoryDefault: 'Installation',
    locationKey: 'feat_loc_unassigned_sort',
    locationDefault: 'Library Top Bar (Auto-Sort)',
    descKey: 'feat_unassigned_sort_desc',
    descDefault:
      '1-click batch analysis that scans unclassified archives in the Unassigned/ folder and re-sorts them to matching character folders using hash detection.',
    icon: FolderCheck,
    badgeColor: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    keywords: ['unassigned', 'auto-assign', 'sort', 're-sort', 'batch', 'resolver'],
  },
  {
    id: 'install_summary_modal',
    num: '15',
    nameKey: 'feat_install_summary_title',
    nameDefault: 'Install Summary & Analysis Report',
    category: 'installation',
    categoryKey: 'features_cat_installation',
    categoryDefault: 'Installation',
    locationKey: 'feat_loc_install_summary',
    locationDefault: 'Post-Install Dialog',
    descKey: 'feat_install_summary_desc',
    descDefault:
      'Detailed post-extraction inspection modal reporting detected character categories, hash matching confidence scores, and conflict alerts.',
    icon: FileCheck,
    badgeColor: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    keywords: ['summary', 'report', 'install', 'confidence', 'post-install', 'modal'],
  },
  {
    id: 'smart_image_sync',
    num: '16',
    nameKey: 'feat_image_sync_title',
    nameDefault: 'Smart Database Image Sync & Bandwidth Optimization',
    category: 'installation',
    categoryKey: 'features_cat_installation',
    categoryDefault: 'Installation',
    locationKey: 'feat_loc_image_sync',
    locationDefault: 'First-Sync Prompt / Settings',
    descKey: 'feat_image_sync_desc',
    descDefault:
      'Intelligent asset synchronizer with space calculation warning (~35 MB), HTTP HEAD content-length cache checking, and fallback icon rendering.',
    icon: Image,
    badgeColor: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
    keywords: ['images', 'sync', 'bandwidth', 'cache', 'portraits', 'download', 'size'],
  },

  // 3. Diagnostics & Health Scanners
  {
    id: 'broken_mod_scanner',
    num: '17',
    nameKey: 'feat_broken_scanner_title',
    nameDefault: 'Tiered Broken Mod Scanner',
    category: 'diagnostics',
    categoryKey: 'features_cat_diagnostics',
    categoryDefault: 'Diagnostics',
    locationKey: 'feat_loc_health_alert',
    locationDefault: 'Library Health Alert / Settings',
    descKey: 'feat_broken_scanner_desc',
    descDefault:
      'Identifies mods rendered unusable by game updates with Tier 1 (Confirmed Outdated via migrations) and Tier 2 (Unverified) diagnostic alerts.',
    icon: ShieldAlert,
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    keywords: ['broken', 'scanner', 'health', 'outdated', 'migration', 'patch', 'update'],
  },
  {
    id: 'keybind_conflicts',
    num: '18',
    nameKey: 'feat_keybinds_title',
    nameDefault: 'Mod Keybinds & Live Conflict Alerts',
    category: 'diagnostics',
    categoryKey: 'features_cat_diagnostics',
    categoryDefault: 'Diagnostics',
    locationKey: 'feat_loc_keybinds',
    locationDefault: 'Mod Card (... → Keybinds)',
    descKey: 'feat_keybinds_desc',
    descDefault:
      'Inspect and edit mod keybinds from the UI, with warnings for overlapping shortcuts.',
    icon: Key,
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    keywords: ['keybind', 'hotkey', 'shortcut', 'conflict', 'ini', 'key'],
  },
  {
    id: 'script_integrity_warnings',
    num: '19',
    nameKey: 'feat_script_warnings_title',
    nameDefault: 'Script Integrity Warnings & 1-Click Auto-Fix',
    category: 'diagnostics',
    categoryKey: 'features_cat_diagnostics',
    categoryDefault: 'Diagnostics',
    locationKey: 'feat_loc_warning_pill',
    locationDefault: 'Mod Card Warning Pill',
    descKey: 'feat_script_warnings_desc',
    descDefault:
      'Detects mod script bugs including rogue HUD erasers, legacy help.ini files, multi-character overlaps, and unconditional hotkeys with 1-click auto-repair.',
    icon: Wrench,
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    keywords: ['warning', 'integrity', 'autofix', 'help.ini', 'script', 'hud', 'repair'],
  },
  {
    id: 'hash_conflict_scanner',
    num: '20',
    nameKey: 'feat_hash_conflict_title',
    nameDefault: 'Component-Aware Hash Conflict Scanner',
    category: 'diagnostics',
    categoryKey: 'features_cat_diagnostics',
    categoryDefault: 'Diagnostics',
    locationKey: 'feat_loc_conflict_pill',
    locationDefault: 'Mod Card Conflict Pill',
    descKey: 'feat_hash_conflict_desc',
    descDefault:
      'Detects when two simultaneously enabled mods override the exact same texture or mesh component, translating raw hashes into readable names.',
    icon: Layers,
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    keywords: ['conflict', 'hash', 'component', 'mesh', 'texture', 'overlap'],
  },
  /*
      {
        id: 'hunting_mode_sniffer',
        num: '21',
        nameKey: 'feat_hunting_mode_title',
        nameDefault: '3DMigoto Hunting Mode & Hash Sniffer',
        category: 'diagnostics',
        categoryKey: 'features_cat_diagnostics',
        categoryDefault: 'Diagnostics',
        locationKey: 'feat_loc_hunting_sniffer',
        locationDefault: 'Settings → Mod Health',
        descKey: 'feat_hunting_mode_desc',
        descDefault:
          'Sniffs and captures runtime vertex and index buffer hashes from d3dx.log during gameplay, cross-referencing against database definitions for easy ingestion.',
        icon: Search,
        badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
        keywords: ['hunting', 'sniffer', 'd3dx', 'log', 'runtime', 'dump', 'hash'],
      },
      */
  {
    id: 'auto_tagger_pow',
    num: '22',
    nameKey: 'feat_auto_tagger_title',
    nameDefault: 'Deterministic Heuristic Auto-Tagger',
    category: 'diagnostics',
    categoryKey: 'features_cat_diagnostics',
    categoryDefault: 'Diagnostics',
    locationKey: 'feat_loc_auto_tagger',
    locationDefault: 'Settings → Mod Health / Mod Card Tags',
    descKey: 'feat_auto_tagger_desc',
    descDefault:
      '100% offline asset classification (#Outfit, #Recolor, #Audio, #Weapon, #UI) by analyzing mod file structures, textures, meshes, and audio containers.',
    icon: Sparkles,
    badgeColor: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
    keywords: ['autotag', 'auto-tagger', 'classification', 'heuristics', 'assets', 'tags'],
  },

  // 4. Game Integration & Tools
  {
    id: 'ingame_hud',
    num: '23',
    nameKey: 'feat_hud_title',
    nameDefault: 'In-Game 3DMigoto HUD Overlay',
    category: 'game',
    categoryKey: 'features_cat_game',
    categoryDefault: 'Game Integration',
    locationKey: 'feat_loc_hud_key',
    locationDefault: 'In-Game (Configured HUD Key)',
    descKey: 'feat_hud_desc',
    descDefault:
      'Dynamically generates an interactive 3DMigoto in-game menu (zzzzzz_ZZZModManagerUI) showing active mods and assigned keybinds accessible by pressing your configured hotkey in-game.',
    icon: Eye,
    badgeColor: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
    keywords: ['hud', 'overlay', 'menu', 'ingame', 'keybind', 'slash'],
  },
  {
    id: 'quick_snapper',
    num: '24',
    nameKey: 'feat_snapper_title',
    nameDefault: 'Quick Snapper (Hotkey Previewer)',
    category: 'game',
    categoryKey: 'features_cat_game',
    categoryDefault: 'Game Integration',
    locationKey: 'feat_loc_quick_snapper',
    locationDefault: 'In-Game (Alt+Shift+S)',
    descKey: 'feat_snapper_desc',
    descDefault:
      'Global OS hotkey capture tool that photographs your currently enabled mod in-game, crops the viewport, saves preview.png, and advances to the next mod.',
    icon: Camera,
    badgeColor: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
    keywords: ['screenshot', 'snap', 'snapper', 'preview', 'hotkey', 'capture'],
  },
  {
    id: 'hot_reload',
    num: '25',
    nameKey: 'feat_hotreload_title',
    nameDefault: 'Real-Time Hot Reload',
    category: 'game',
    categoryKey: 'features_cat_game',
    categoryDefault: 'Game Integration',
    locationKey: 'feat_loc_hot_reload',
    locationDefault: 'Automatic on Mod Toggle',
    descKey: 'feat_hotreload_desc',
    descDefault:
      'Automatically focuses ZZZ and dispatches the 3DMigoto F10 reload key when mod states change while the game is running.',
    icon: Flame,
    badgeColor: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
    keywords: ['hotreload', 'reload', 'f10', 'realtime', 'instant', 'refresh'],
  },
  {
    id: 'mod_splitter',
    num: '26',
    nameKey: 'feat_splitter_title',
    nameDefault: 'Mod Splitter',
    category: 'tools',
    categoryKey: 'features_cat_tools',
    categoryDefault: 'Tools',
    locationKey: 'feat_loc_mod_splitter',
    locationDefault: 'Mod Card (... → Split Mod)',
    descKey: 'feat_splitter_desc',
    descDefault:
      'Decompiles composite multi-character mod packages into clean, independent single-character mod folders with preserved shader and texture dependencies.',
    icon: Scissors,
    badgeColor: 'bg-pink-500/10 text-pink-400 border-pink-500/20',
    keywords: ['split', 'splitter', 'decompile', 'multi-character', 'extract', 'separate'],
  },
  {
    id: 'mod_randomizer',
    num: '27',
    nameKey: 'feat_randomizer_title',
    nameDefault: 'Mod Randomizer',
    category: 'tools',
    categoryKey: 'features_cat_tools',
    categoryDefault: 'Tools',
    locationKey: 'feat_loc_randomizer',
    locationDefault: 'Library Top Bar (Randomize)',
    descKey: 'feat_randomizer_desc',
    descDefault:
      'Automatically selects and enables random mod loadouts across whitelisted character categories with favorite weightings.',
    icon: Shuffle,
    badgeColor: 'bg-pink-500/10 text-pink-400 border-pink-500/20',
    keywords: ['random', 'randomizer', 'shuffle', 'roll', 'preset', 'weights'],
  },
  {
    id: 'image_cropper',
    num: '28',
    nameKey: 'feat_cropper_title',
    nameDefault: 'In-App Canvas Image Cropper',
    category: 'tools',
    categoryKey: 'features_cat_tools',
    categoryDefault: 'Tools',
    locationKey: 'feat_loc_image_cropper',
    locationDefault: 'Mod Card Drop / Menu',
    descKey: 'feat_cropper_desc',
    descDefault:
      'Interactive canvas-based pan, zoom, and aspect-ratio locked image cropper (1:1, 16:9, 3:4, Free) with 90-degree rotation for crisp preview cards.',
    icon: Crop,
    badgeColor: 'bg-pink-500/10 text-pink-400 border-pink-500/20',
    keywords: ['crop', 'cropper', 'canvas', 'image', 'preview', 'aspect', 'zoom'],
  },
  {
    id: 'mod_viewer_3d',
    num: '29',
    nameKey: 'feat_3d_viewer_title',
    nameDefault: 'In-App 3D Mod Previewer',
    category: 'tools',
    categoryKey: 'features_cat_tools',
    categoryDefault: 'Tools',
    locationKey: 'feat_loc_3d_viewer',
    locationDefault: 'Mod Card (... → Preview 3D)',
    descKey: 'feat_3d_viewer_desc',
    descDefault:
      'Interactive Three.js 3D viewport parsing raw 3DMigoto vertex/index binary buffers, auto-detecting Float16/Float32 UVs, with orbit camera, wireframe, and diffuse texturing.',
    icon: Box,
    badgeColor: 'bg-pink-500/10 text-pink-400 border-pink-500/20',
    keywords: ['3d', 'viewer', 'preview', 'threejs', 'mesh', 'model', 'wireframe'],
  },
  {
    id: 'direct_game_launcher',
    num: '30',
    nameKey: 'feat_launcher_title',
    nameDefault: 'Direct Game Launcher',
    category: 'game',
    categoryKey: 'features_cat_game',
    categoryDefault: 'Game Integration',
    locationKey: 'feat_loc_game_launcher',
    locationDefault: 'Top Bar (Launch Game)',
    descKey: 'feat_launcher_desc',
    descDefault:
      'Launches Zenless Zone Zero directly through the XXMI Launcher with support for custom command-line arguments (e.g. --nogui).',
    icon: Play,
    badgeColor: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
    keywords: ['launch', 'play', 'game', 'xxmi', 'nogui', 'start'],
  },
  {
    id: 'char_filters',
    num: '31',
    nameKey: 'feat_char_filters_title',
    nameDefault: 'Subcategory Switcher & Attribute Filters',
    category: 'library',
    categoryKey: 'features_cat_library',
    categoryDefault: 'Library',
    locationKey: 'feat_loc_char_filters',
    locationDefault: 'Character View Toolbar',
    descKey: 'feat_char_filters_desc',
    descDefault:
      'Filter character categories by combat Element (Electric, Fire, Ice, Physical, Ether), in-game Faction, Gender, and Model Archetype.',
    icon: Filter,
    badgeColor: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
    keywords: ['filter', 'element', 'faction', 'gender', 'model', 'attribute', 'character'],
  },

  // 5. GameBanana Discover & Downloader
  {
    id: 'gamebanana_discover',
    num: '32',
    nameKey: 'feat_gb_discover_title',
    nameDefault: 'GameBanana Discover & Search',
    category: 'discover',
    categoryKey: 'features_cat_discover',
    categoryDefault: 'Discover',
    locationKey: 'feat_loc_discover_nav',
    locationDefault: 'Top Navigation (Discover)',
    descKey: 'feat_gb_discover_desc',
    descDefault:
      'In-app browser to explore, search, and filter thousands of mods directly from the GameBanana v13 API with screenshots, tags, author info, and rich descriptions.',
    icon: Compass,
    badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
    keywords: ['gamebanana', 'discover', 'browse', 'search', 'online', 'feed'],
  },
  {
    id: 'gb_nested_categories',
    num: '33',
    nameKey: 'feat_gb_nested_title',
    nameDefault: 'Nested Category Tree & Portrait Enrichment',
    category: 'discover',
    categoryKey: 'features_cat_discover',
    categoryDefault: 'Discover',
    locationKey: 'feat_loc_gb_nested',
    locationDefault: 'Discover Sidebar',
    descKey: 'feat_gb_nested_desc',
    descDefault:
      'Browse GameBanana by character, skin, and subcategory using icons from your local library.',
    icon: FolderGit2,
    badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
    keywords: ['gamebanana', 'nested', 'categories', 'portraits', 'tree', 'aliases'],
  },
  {
    id: 'community_announcements_polls',
    num: '34',
    nameKey: 'feat_community_feed_title',
    nameDefault: 'Community Live Announcements & Dynamic Polls',
    category: 'discover',
    categoryKey: 'features_cat_discover',
    categoryDefault: 'Discover',
    locationKey: 'feat_loc_community_feed',
    locationDefault: 'Discover Feed Header',
    descKey: 'feat_community_feed_desc',
    descDefault:
      'Interactive community banner in the Discover feed displaying cloud announcements and interactive feature polls with direct link voting.',
    icon: Radio,
    badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
    keywords: ['community', 'announcements', 'polls', 'voting', 'feed', 'banner'],
  },
  {
    id: 'gamebanana_downloader',
    num: '35',
    nameKey: 'feat_gb_download_title',
    nameDefault: 'Resilient Multi-Threaded Downloader',
    category: 'discover',
    categoryKey: 'features_cat_discover',
    categoryDefault: 'Discover',
    locationKey: 'feat_loc_download_btn',
    locationDefault: 'Discover Download Button',
    descKey: 'feat_gb_download_desc',
    descDefault:
      'Asynchronous download manager with real-time speed, ETA calculation, and Tokio retry loops with backoff to gracefully handle connection timeouts.',
    icon: Download,
    badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
    keywords: ['download', 'downloader', 'retry', 'speed', 'eta', 'async'],
  },
  {
    id: 'mod_update_checker',
    num: '36',
    nameKey: 'feat_update_checker_title',
    nameDefault: 'Automatic Mod Update Checker',
    category: 'discover',
    categoryKey: 'features_cat_discover',
    categoryDefault: 'Discover',
    locationKey: 'feat_loc_update_badge',
    locationDefault: 'Top Bar / Mod Card Badges',
    descKey: 'feat_update_checker_desc',
    descDefault:
      'Compares installed mod timestamps with GameBanana API endpoints to detect and alert when newer mod versions are released, with sidebar badge counters.',
    icon: RefreshCw,
    badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
    keywords: ['update', 'checker', 'new', 'version', 'gamebanana', 'badge'],
  },
  {
    id: 'nsfw_filters',
    num: '37',
    nameKey: 'feat_nsfw_filter_title',
    nameDefault: 'NSFW Content Controls & Thumbnail Blurring',
    category: 'discover',
    categoryKey: 'features_cat_discover',
    categoryDefault: 'Discover',
    locationKey: 'feat_loc_nsfw_filter',
    locationDefault: 'Settings → Discover',
    descKey: 'feat_nsfw_filter_desc',
    descDefault:
      'Global NSFW filter toggle to hide mature mods completely, paired with thumbnail blurring mode to preview Discover feeds safely.',
    icon: EyeOff,
    badgeColor: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
    keywords: ['nsfw', 'filter', 'blur', 'mature', 'safety', 'thumbnails'],
  },

  // 6. Customization, Accessibility & Theming
  {
    id: 'theme_customizer',
    num: '38',
    nameKey: 'feat_themes_title',
    nameDefault: 'Theme Modes (Dark, Light, Glass)',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_appearance',
    locationDefault: 'Settings → Customization',
    descKey: 'feat_themes_desc',
    descDefault:
      'Fully integrated visual themes including Dark Slate, Light Mode, and a specialized Deep Violet Glass acrylic theme (15, 10, 25) tuned for anime wallpapers.',
    icon: Palette,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['theme', 'color', 'glass', 'dark', 'light', 'acrylic', 'appearance'],
  },
  {
    id: 'accent_color_picker',
    num: '39',
    nameKey: 'feat_color_picker_title',
    nameDefault: 'Preset Accent Colors & Native OS Color Picker',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_color_picker',
    locationDefault: 'Settings → Customization',
    descKey: 'feat_color_picker_desc',
    descDefault:
      '14+ themed preset accent colors (Azure, Emerald, Neon Pink, Pastel Lilac, Sakura Pink, etc.) plus a native OS color picker for any 24-bit hex color.',
    icon: Pipette,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['color', 'picker', 'accent', 'azure', 'pink', 'hex', 'palette'],
  },
  {
    id: 'wallpaper_controls',
    num: '40',
    nameKey: 'feat_wallpaper_title',
    nameDefault: 'Custom Wallpaper & Background Controls',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_wallpaper',
    locationDefault: 'Settings → Customization',
    descKey: 'feat_wallpaper_desc',
    descDefault:
      'Upload custom wallpapers with fine controls for blur intensity, saturation, brightness, image fit (cover, contain, fill), and opacity sliders.',
    icon: Image,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['wallpaper', 'background', 'blur', 'saturation', 'brightness', 'opacity'],
  },
  {
    id: 'ui_scale_card_size',
    num: '41',
    nameKey: 'feat_ui_scale_title',
    nameDefault: 'UI Scaling & Mod Card Size Customizer',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_ui_scale',
    locationDefault: 'Settings → Customization',
    descKey: 'feat_ui_scale_desc',
    descDefault:
      'Full interface zoom slider (75% to 125%) and dynamic mod card dimensions slider (150px to 400px) to suit any monitor resolution.',
    icon: Sliders,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['scale', 'zoom', 'card', 'size', 'dimensions', 'resolution'],
  },
  {
    id: 'reduced_motion_mode',
    num: '42',
    nameKey: 'feat_reduced_motion_title',
    nameDefault: 'Reduced Motion Accessibility Mode',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_reduced_motion',
    locationDefault: 'Settings → Customization',
    descKey: 'feat_reduced_motion_desc',
    descDefault:
      'Toggle animations off (data-no-motion="true") to bypass Framer Motion and CSS transitions for lower resource usage and accessibility.',
    icon: Zap,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['motion', 'animation', 'performance', 'accessibility', 'reduced', 'smooth'],
  },
  {
    id: 'language_hub',
    num: '43',
    nameKey: 'feat_language_hub_title',
    nameDefault: 'Language Hub, Pack Generator & Hot-Reload',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_language_hub',
    locationDefault: 'Settings → Customization',
    descKey: 'feat_language_hub_desc',
    descDefault:
      'Full internationalization suite with 1-click template.json generation in AppData, directory opening, and live hot-reloading without restarting the app.',
    icon: Languages,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['language', 'i18n', 'translation', 'translator', 'locale', 'export', 'import'],
  },
  {
    id: 'first_run_language_select',
    num: '44',
    nameKey: 'feat_lang_select_title',
    nameDefault: 'First-Run Language Selection Wizard',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_lang_select',
    locationDefault: 'Startup Onboarding',
    descKey: 'feat_lang_select_desc',
    descDefault: 'Language selection screen shown before starting the setup wizard.',
    icon: Languages,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['language', 'first-run', 'onboarding', 'wizard', 'select', 'locale'],
  },

  // 7. Gamification & Onboarding
  {
    id: 'achievements_system',
    num: '45',
    nameKey: 'feat_achievements_title',
    nameDefault: 'Interactive Achievements & Progression',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_achievements',
    locationDefault: 'Top Navigation (Achievements)',
    descKey: 'feat_achievements_desc',
    descDefault:
      'Gamified progression system with 25+ unlockable achievements, live real-time progress bars, expandable step guides, and celebration confetti.',
    icon: Trophy,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['achievements', 'trophy', 'progression', 'gamification', 'progress', 'confetti'],
  },
  {
    id: 'tutorials_onboarding',
    num: '46',
    nameKey: 'feat_tutorials_title',
    nameDefault: 'Interactive Onboarding & Tutorials',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_tutorials',
    locationDefault: 'First Launch / Settings → Tutorials',
    descKey: 'feat_tutorials_desc',
    descDefault:
      'First-run setup assistant and modal tutorial guides with pulsing colored button borders guiding users through folder setup and key features.',
    icon: GraduationCap,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['tutorial', 'onboarding', 'guide', 'setup', 'help', 'wizard'],
  },
  {
    id: 'feature_showcase_qa',
    num: '47',
    nameKey: 'feat_showcase_qa_title',
    nameDefault: 'Feature List and QA Tracker',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_showcase_qa',
    locationDefault: 'Settings → Feature List',
    descKey: 'feat_showcase_qa_desc',
    descDefault:
      'Interactive visual catalog in Settings with search, category filters, and an interactive QA checklist to test and verify every app capability.',
    icon: FlaskConical,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['showcase', 'catalog', 'qa', 'test', 'checklist', 'features'],
  },

  // 8. System, Safety & Deployment
  {
    id: 'safe_storage',
    num: '48',
    nameKey: 'feat_storage_title',
    nameDefault: 'Safe Storage & Versioned Migrations',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_startup',
    locationDefault: 'Startup Lifecycle',
    descKey: 'feat_storage_desc',
    descDefault:
      'Hardened localStorage wrapper preventing crashes from corrupted data, paired with automated schema migrations across releases.',
    icon: HardDrive,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['storage', 'safe', 'migration', 'schema', 'persistence', 'localStorage'],
  },
  {
    id: 'backup_restore',
    num: '49',
    nameKey: 'feat_backup_title',
    nameDefault: 'Full Backup & Restore',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_backup_settings',
    locationDefault: 'Settings → Advanced',
    descKey: 'feat_backup_desc',
    descDefault:
      '1-click export and import of all configured paths, custom themes, hotkeys, warning rules, and mod profiles into a portable .json backup file.',
    icon: Save,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['backup', 'restore', 'export', 'import', 'settings', 'json'],
  },
  {
    id: 'folder_watcher',
    num: '50',
    nameKey: 'feat_watcher_title',
    nameDefault: 'Live Directory Watcher',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_watcher',
    locationDefault: 'Background Watcher',
    descKey: 'feat_watcher_desc',
    descDefault:
      'Watches the active XXMI Mods folder for external additions, deletions, or renames and automatically refreshes library state without polling.',
    icon: Folder,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['watcher', 'folder', 'filesystem', 'notify', 'live', 'refresh'],
  },
  {
    id: 'dual_auto_updater',
    num: '51',
    nameKey: 'feat_signed_updater_title',
    nameDefault: 'Dual In-App Auto-Updater',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_signed_updater',
    locationDefault: 'Global Notification Banner',
    descKey: 'feat_signed_updater_desc',
    descDefault:
      'Checks GitHub for new releases, verifies file signatures with Minisign, and updates the app.',
    icon: ShieldCheck,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['updater', 'auto-updater', 'minisign', 'signature', 'release', 'upgrade'],
  },
  {
    id: 'notifications_hub',
    num: '52',
    nameKey: 'feat_notifications_title',
    nameDefault: 'Release Notifications & Announcement Hub',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_notifications',
    locationDefault: 'Sidebar Bell (Notifications)',
    descKey: 'feat_notifications_desc',
    descDefault:
      'In-app notification center querying remote notifications.json for new version release announcements, patch notes, and community alerts.',
    icon: Bell,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['notifications', 'announcements', 'changelog', 'news', 'bell', 'updates'],
  },
  {
    id: 'danger_zone_reset',
    num: '53',
    nameKey: 'feat_danger_zone_title',
    nameDefault: 'Danger Zone & System Reset Controls',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_danger_zone',
    locationDefault: 'Settings → Danger Zone',
    descKey: 'feat_danger_zone_desc',
    descDefault:
      'Dedicated recovery panel in Settings to reset all settings to defaults, wipe local AppData database/images cache, and force-clear corrupted snapshots.',
    icon: AlertOctagon,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['danger', 'reset', 'wipe', 'cache', 'appdata', 'factory'],
  },
  {
    id: 'retro_nsis_installer',
    num: '54',
    nameKey: 'feat_nsis_installer_title',
    nameDefault: 'Retro 2000s Anime NSIS Installer & Clean Uninstaller',
    category: 'system',
    categoryKey: 'features_cat_system',
    categoryDefault: 'System & Safety',
    locationKey: 'feat_loc_nsis_installer',
    locationDefault: 'Windows Setup (.exe)',
    descKey: 'feat_nsis_installer_desc',
    descDefault:
      'Custom NSIS Windows installer with full-screen BGGradient (Black to Deep Purple), custom anime sidebar/header BMP banners, retro styling, and clean uninstaller checkbox.',
    icon: Archive,
    badgeColor: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
    keywords: ['installer', 'nsis', 'setup', 'uninstall', 'cleanup', 'gradient', 'retro'],
  },
];
