import {
  Rocket,
  Trash2,
  Keyboard,
  Download,
  Archive,
  Box,
  Package,
  GraduationCap,
  Cloud,
  MousePointerClick,
  ShoppingCart,
  RefreshCw,
  Flame,
} from 'lucide-react';
import { useAppStore, TUTORIALS_LIST } from '../../store/useAppStore';
import type { AchievementDef } from './types';
import { TUTORIAL_TARGET_MAP } from './types';

export const BASICS_AND_COLLECTION_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'first_steps',
    title: 'First Steps',
    description: 'Launch the game from the manager for the first time.',
    icon: Rocket,
    target: 1,
    category: 'basics',
    getProgress: (s) => s.gameLaunches,
    navigationTarget: { tab: 'library', highlightId: 'launch_game_btn' },
    steps: [
      'achievement_first_steps_step_1',
      'achievement_first_steps_step_2',
      'achievement_first_steps_step_3',
    ],
  },
  {
    id: 'spring_cleaning',
    title: 'Spring Cleaning',
    description: 'Delete a mod for the first time.',
    icon: Trash2,
    target: 1,
    category: 'basics',
    getProgress: (s) => s.modsDeleted,
    navigationTarget: { tab: 'library', highlightId: 'first_mod_delete' },
    steps: [
      'achievement_spring_cleaning_step_1',
      'achievement_spring_cleaning_step_2',
      'achievement_spring_cleaning_step_3',
    ],
  },
  {
    id: 'control_freak',
    title: 'Control Freak',
    description: 'Change keybinds 5 times.',
    icon: Keyboard,
    target: 5,
    category: 'basics',
    getProgress: (s) => s.keybindsChanged,
    navigationTarget: { tab: 'library', highlightId: 'first_mod_keybinds' },
    steps: [
      'achievement_control_freak_step_1',
      'achievement_control_freak_step_2',
      'achievement_control_freak_step_3',
    ],
  },
  {
    id: 'cloud_synchronizer',
    title: 'Cloud Synchronizer',
    description: "Use the 'Sync Cloud DB' button.",
    icon: Cloud,
    target: 1,
    category: 'basics',
    getProgress: (s) => s.cloudSyncs,
    navigationTarget: { tab: 'library', highlightId: 'sync_cloud_db_btn' },
    steps: ['achievement_cloud_sync_step_1', 'achievement_cloud_sync_step_2'],
  },
  {
    id: 'tutorial_scholar',
    title: 'Tutorial Scholar',
    description: `Discover and read all ${TUTORIALS_LIST.length} interactive onboarding tutorials.`,
    icon: GraduationCap,
    target: TUTORIALS_LIST.length,
    category: 'basics',
    getProgress: (_, t) => t,
    navigationTarget: () => {
      const seen = useAppStore.getState().tutorialsSeen || {};
      const firstUnseen = TUTORIALS_LIST.find((id) => !seen[id]);
      if (firstUnseen && TUTORIAL_TARGET_MAP[firstUnseen]) {
        return TUTORIAL_TARGET_MAP[firstUnseen];
      }
      return {
        tab: 'settings',
        settingsTab: 'general',
        highlightId: 'tutorial_settings',
      };
    },
    steps: [
      'achievement_tutorial_scholar_step_1',
      'achievement_tutorial_scholar_step_2',
      'achievement_tutorial_scholar_step_3',
    ],
  },

  // 2. Collection & Downloads,
  {
    id: 'www',
    title: 'World Wide Web',
    description: 'Install 10 mods directly from GameBanana.',
    icon: Download,
    target: 10,
    category: 'collection',
    getProgress: (s) => s.modsInstalledGB,
    navigationTarget: { tab: 'gamebanana', highlightId: 'gamebanana_search' },
    steps: ['achievement_www_step_1', 'achievement_www_step_2', 'achievement_www_step_3'],
  },
  {
    id: 'collector',
    title: 'The Collector',
    description: 'Install 25 mods from any source.',
    icon: Box,
    target: 25,
    category: 'collection',
    getProgress: (s) => s.modsInstalledLocal + s.modsInstalledGB,
    navigationTarget: { tab: 'gamebanana', highlightId: 'gamebanana_search' },
    steps: ['achievement_collector_step_1', 'achievement_collector_step_2'],
  },
  {
    id: 'hoarder',
    title: 'The Hoarder',
    description: 'Install 50 mods from any source.',
    icon: Package,
    target: 50,
    category: 'collection',
    getProgress: (s) => s.modsInstalledLocal + s.modsInstalledGB,
    navigationTarget: { tab: 'gamebanana', highlightId: 'gamebanana_search' },
    steps: ['achievement_hoarder_step_1', 'achievement_hoarder_step_2'],
  },
  {
    id: 'archivist',
    title: 'The Archivist',
    description: 'Install 100 mods from any source.',
    icon: Archive,
    target: 100,
    category: 'collection',
    getProgress: (s) => s.modsInstalledLocal + s.modsInstalledGB,
    navigationTarget: { tab: 'gamebanana', highlightId: 'gamebanana_search' },
    steps: ['achievement_archivist_step_1', 'achievement_archivist_step_2'],
  },
  {
    id: 'drag_master',
    title: 'Drag Master',
    description: 'Install a mod via drag & drop.',
    icon: MousePointerClick,
    target: 1,
    category: 'collection',
    getProgress: (s) => s.modsInstalledDragDrop,
    navigationTarget: { tab: 'library' },
    steps: ['achievement_drag_master_step_1', 'achievement_drag_master_step_2'],
  },
  {
    id: 'speed_runner',
    title: 'Speed Runner',
    description: 'Install 5 mods via drag & drop.',
    icon: Flame,
    target: 5,
    category: 'collection',
    getProgress: (s) => s.modsInstalledDragDrop,
    navigationTarget: { tab: 'library' },
    steps: ['achievement_speed_runner_step_1', 'achievement_speed_runner_step_2'],
  },
  {
    id: 'smart_shopper',
    title: 'Smart Shopper',
    description: 'Use the Smart Download category picker.',
    icon: ShoppingCart,
    target: 1,
    category: 'collection',
    getProgress: (s) => s.smartDownloadsUsed,
    navigationTarget: { tab: 'gamebanana', highlightId: 'gamebanana_search' },
    steps: [
      'achievement_smart_shopper_step_1',
      'achievement_smart_shopper_step_2',
      'achievement_smart_shopper_step_3',
      'achievement_smart_shopper_step_4',
    ],
  },
  {
    id: 'completionist',
    title: 'The Completionist',
    description: 'Update a mod via the Update Checker.',
    icon: RefreshCw,
    target: 1,
    category: 'collection',
    getProgress: (s) => s.modsUpdated,
    navigationTarget: { tab: 'library', highlightId: 'check_updates_btn' },
    steps: ['achievement_completionist_step_1', 'achievement_completionist_step_2'],
  },

  // 3. Library & Management,
];
