import {
  Camera,
  Dices,
  Box,
  Sparkles,
  Star,
  Filter,
  StickyNote,
  CheckCheck,
  Search,
  BookOpen,
  Shield,
  Scissors,
  Crop,
  Tag,
  Wrench,
  Link,
  FolderCheck,
} from 'lucide-react';
import { useAppStore } from '../../store/useAppStore';
import type { AchievementDef } from './types';

export const MANAGEMENT_AND_TOOLS_ACHIEVEMENTS: AchievementDef[] = [
  {
    id: 'fashionista',
    title: 'Fashionista',
    description: 'Toggle or enable 50 different mods in the library.',
    icon: Sparkles,
    target: 50,
    category: 'management',
    getProgress: (s) => s.modsToggled,
    navigationTarget: { tab: 'library', highlightId: 'first_mod_toggle' },
    steps: ['achievement_fashionista_step_1', 'achievement_fashionista_step_2'],
  },
  {
    id: 'star_struck',
    title: 'Star Struck',
    description: 'Favorite 5 different characters or mods.',
    icon: Star,
    target: 5,
    category: 'management',
    getProgress: () =>
      useAppStore.getState().favoriteCategories.length + useAppStore.getState().favoriteMods.length,
    navigationTarget: { tab: 'library', highlightId: 'first_mod_options' },
    steps: ['achievement_star_struck_step_1', 'achievement_star_struck_step_2'],
  },
  {
    id: 'note_taker',
    title: 'Note Taker',
    description: 'Write your first mod note.',
    icon: StickyNote,
    target: 1,
    category: 'management',
    getProgress: (s) => s.notesWritten,
    navigationTarget: { tab: 'library', highlightId: 'first_mod_options' },
    steps: [
      'achievement_note_taker_step_1',
      'achievement_note_taker_step_2',
      'achievement_note_taker_step_3',
    ],
  },
  {
    id: 'librarian',
    title: 'The Librarian',
    description: 'Write 10 mod notes across your collection.',
    icon: BookOpen,
    target: 10,
    category: 'management',
    getProgress: (s) => s.notesWritten,
    navigationTarget: { tab: 'library', highlightId: 'first_mod_options' },
    steps: ['achievement_librarian_step_1', 'achievement_librarian_step_2'],
  },
  {
    id: 'batch_commander',
    title: 'Batch Commander',
    description: 'Use Batch Mode to act on 5+ mods at once.',
    icon: CheckCheck,
    target: 1,
    category: 'management',
    getProgress: (s) => s.batchOpsPerformed,
    navigationTarget: { tab: 'library', highlightId: 'batch_mode_toggle' },
    steps: [
      'achievement_batch_commander_step_1',
      'achievement_batch_commander_step_2',
      'achievement_batch_commander_step_3',
      'achievement_batch_commander_step_4',
    ],
  },
  {
    id: 'detective',
    title: 'The Detective',
    description: 'Use Global Search to find a mod across all categories.',
    icon: Search,
    target: 1,
    category: 'management',
    getProgress: (s) => s.globalSearchesUsed,
    navigationTarget: { tab: 'library', highlightId: 'character_filter_bar' },
    steps: [
      'achievement_detective_step_1',
      'achievement_detective_step_2',
      'achievement_detective_step_3',
      'achievement_detective_step_4',
    ],
  },
  {
    id: 'picky_selector',
    title: 'Picky Selector',
    description: 'Use the Character Filters (Element, Faction, etc.) to filter the library.',
    icon: Filter,
    target: 1,
    category: 'management',
    getProgress: (s) => s.filtersUsed,
    navigationTarget: { tab: 'library', highlightId: 'character_filter_bar' },
    steps: ['achievement_picky_selector_step_1', 'achievement_picky_selector_step_2'],
  },
  {
    id: 'cartographer',
    title: 'Cartographer',
    description: 'Link a custom disk folder to a character using the Category Mapping Modal.',
    icon: Link,
    target: 1,
    category: 'management',
    getProgress: (s) => s.categoryMapped,
    navigationTarget: { tab: 'library', highlightId: 'map_category_btn' },
    steps: [
      'achievement_cartographer_step_1',
      'achievement_cartographer_step_2',
      'achievement_cartographer_step_3',
    ],
  },
  {
    id: 'smart_assigner',
    title: 'Smart Assigner',
    description: 'Auto-sort unassigned mods from the Unassigned folder with 1 click.',
    icon: FolderCheck,
    target: 1,
    category: 'management',
    getProgress: (s) => s.autoSortsUsed,
    navigationTarget: { tab: 'library', highlightId: 'auto_assign_btn' },
    steps: ['achievement_smart_assigner_step_1', 'achievement_smart_assigner_step_2'],
  },
  {
    id: 'tag_champion',
    title: 'Tag Champion',
    description: 'Add custom tags or auto-detect tags on 5 mods.',
    icon: Tag,
    target: 5,
    category: 'management',
    getProgress: (s) => s.tagsEdited,
    navigationTarget: { tab: 'library', highlightId: 'first_mod_options' },
    steps: [
      'achievement_tag_champion_step_1',
      'achievement_tag_champion_step_2',
      'achievement_tag_champion_step_3',
    ],
  },

  // 4. Advanced Modding Tools,
  {
    id: 'trigger_happy',
    title: 'Trigger Happy',
    description: 'Take 10 screenshots using the Quick Snapper.',
    icon: Camera,
    target: 10,
    category: 'tools',
    getProgress: (s) => s.quickSnapsTaken,
    navigationTarget: {
      tab: 'settings',
      settingsTab: 'in_game',
      highlightId: 'quick_snapper_settings',
    },
    steps: [
      'achievement_trigger_happy_step_1',
      'achievement_trigger_happy_step_2',
      'achievement_trigger_happy_step_3',
    ],
  },
  {
    id: 'chaos_theory',
    title: 'Chaos Theory',
    description:
      'Configure character whitelist in Settings → Randomizer and shuffle active mods 10 times in the Library.',
    icon: Dices,
    target: 10,
    category: 'tools',
    getProgress: (s) => s.randomizeCount,
    navigationTarget: () => {
      const whitelist = useAppStore.getState().randomizerWhitelist;
      if (!whitelist || whitelist.length === 0) {
        return {
          tab: 'settings',
          settingsTab: 'library',
          highlightId: 'randomizer_settings',
        };
      }
      return { tab: 'library', highlightId: 'randomize_button' };
    },
    steps: [
      'achievement_chaos_theory_step_1',
      'achievement_chaos_theory_step_2',
      'achievement_chaos_theory_step_3',
      'achievement_chaos_theory_step_4',
    ],
  },
  {
    id: 'dimension_walker',
    title: 'Dimension Walker',
    description: 'Preview a character mod in the interactive 3D Mod Viewer.',
    icon: Box,
    target: 1,
    category: 'tools',
    getProgress: (s) => s.previews3d,
    navigationTarget: { tab: 'library', highlightId: 'first_mod_options' },
    steps: [
      'achievement_dimension_walker_step_1',
      'achievement_dimension_walker_step_2',
      'achievement_dimension_walker_step_3',
    ],
  },
  {
    id: 'master_surgeon',
    title: 'Master Surgeon',
    description: 'Decompile a multi-character composite mod using the Mod Splitter.',
    icon: Scissors,
    target: 1,
    category: 'tools',
    getProgress: (s) => s.modsSplit,
    navigationTarget: { tab: 'library', highlightId: 'first_mod_options' },
    steps: [
      'achievement_master_surgeon_step_1',
      'achievement_master_surgeon_step_2',
      'achievement_master_surgeon_step_3',
    ],
  },
  {
    id: 'pixel_perfect',
    title: 'Pixel Perfect',
    description: 'Crop and save a custom preview card using the In-App Canvas Cropper.',
    icon: Crop,
    target: 1,
    category: 'tools',
    getProgress: (s) => s.imagesCropped,
    navigationTarget: { tab: 'library', highlightId: 'first_mod_options' },
    steps: [
      'achievement_pixel_perfect_step_1',
      'achievement_pixel_perfect_step_2',
      'achievement_pixel_perfect_step_3',
    ],
  },
  {
    id: 'self_healing',
    title: 'Self-Healing Modder',
    description: 'Use the 1-Click Auto-Fix tool to repair a problematic mod script.',
    icon: Wrench,
    target: 1,
    category: 'tools',
    getProgress: (s) => s.warningsFixed,
    navigationTarget: { tab: 'library', highlightId: 'first_mod_options' },
    steps: [
      'achievement_self_healing_step_1',
      'achievement_self_healing_step_2',
      'achievement_self_healing_step_3',
    ],
  },
  {
    id: 'conflict_resolver',
    title: 'Conflict Resolver',
    description: 'View a keybind or mesh hash conflict warning.',
    icon: Shield,
    target: 1,
    category: 'tools',
    getProgress: (s) => s.conflictsViewed,
    navigationTarget: { tab: 'library', highlightId: 'first_mod_options' },
    steps: ['achievement_conflict_resolver_step_1', 'achievement_conflict_resolver_step_2'],
  },
];
